spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: r1
              uri: lb://customer-service
              predicates:
                - Path= /customers/**
            - id: r2
              uri: lb://inventory-service
              predicates:
                - Path= /products/**
            - id: r3
              uri: lb://billing-service
              predicates:
                - Path= /api/bills/**, /api/productsItems/**, /bills/**, /productItems/**